branch-defaults:
  master:
    environment: di2-front-end-test
    group_suffix: null
global:
  application_name: di2-front-end
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  #profile: di2-front-end-render
  repository: null
  sc: git
  workspace_type: Application